version: 2
jobs:
  build:
    docker:
      - image: textile/circleci:1.10
    working_directory: /go/src/github.com/textileio/textile-go
    steps:
      - checkout
      - run: dep ensure
      - run: npm test
