version: 2
jobs:
  build:
    docker:
      - image: textile/circleci:1.10
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: npm run setup
      - run: npm test
